### ISSUE TITLE
Add slight opacity on toggle

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/bamboo#1]
The toggle has a white background on small screens:

![Screen Shot 2019-11-08 at 8 48 51 AM](https://user-images.githubusercontent.com/871421/68485421-e696f900-0204-11ea-8754-e00afc547425.jpg)

Would it work with just a slight transparency so whatever is underneath still shows through just a bit? Might make it feel less choppy. Or maybe with positioning so that it doesn't overlap titles or content below.

**Comment by laryn** [comment]
I see, it's fixed there on scrolling (nice!) so maybe the opacity is the best option, if you agree.

**Comment by ghost** [comment]
At first I didn't have any background, because styling should be done by the theme, but then I added a basic white background so the button wouldn't be hidden on darker pages/content.

I feel to leave styling up to the theme/site, but I guess if you want to use this layout with an existing theme it should look nicer, right?

**Comment by laryn** [comment]
Totally up to you, just my initial impressions. I would say just a few defaults that work relatively well across themes would be helpful as a starting point -- your call as to whether this would be included in that.

**Comment by ghost** [comment]
Yes, I'm tending to agree with you. Its no harder for a theme to override a translucent background than an opaque one 😊

**Comment by ghost** [comment]
Made a PR, please let me know what you think: https://github.com/backdrop-contrib/bamboo/pull/3

**Comment by laryn** [comment]
LGTM. As you say, this will probably be overridden in the theme by many, but I think this is a good starting point and should look clean across a variety of themes.

**Comment by ghost** [comment]
Thanks, committed!
