### ISSUE TITLE
Use bootstrap layout classes?

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/bamboo#5]
Hey, nice layout! I've been looking for a Off-canvas menu for Backdrop for a long time, and this layout would do the trick.

Is there a particular reason why you didn't use the layout classes provided by Backdrop core like `col-md-3` for the sidebar and respectively for the content area?

I'm not sure if using such classes would make the styling more complex, but I see potential advantages, especially compatibility with (or portability to) core layouts like Moscone.

**Comment by ghost** [comment]
> Is there a particular reason why you didn't use the layout classes provided by Backdrop core...

I'm not very familiar with grid systems (or whatever Bootstrap is) and instead prefer to use CSS Flexbox/Grids. However in this case, with only two regions, simple floats/positioning did the trick nicely.

> I see potential advantages, especially compatibility with (or portability to) core layouts like Moscone.

Not sure what you mean by 'compatibility/portability'... If you use Moscone, or any other core layout, then you're not using Bamboo, so compatibility doesn't come into it. Right? Or have I mis-understood you?

**Comment by olafgrabienski** [comment]
> If you use Moscone, or any other core layout, then you're not using Bamboo, so compatibility doesn't come into it. Right? Or have I mis-understood you?

I guess I'd like to use the sidebar behavior of Bamboo in a (custom) core layout. Sure, I can try to adapt it personally. However, if Bamboo was built similar to a core layout, I imagine using and adapting it to different needs (e.g. more regions, or more flexibile breakpoints) would be more easy. However, I understand perfectly if that's not your intention, hence the original question. *Bamboo* is anyway a helpful inspiration for me.

**Comment by ghost** [comment]
Yeah sorry, don't think I'll be changing Bamboo to use Bootstrap classes.

Sounds like you might be looking for a module that can do sidebar collapse fanciness across multiple layouts... Not sure if/how that'd work though. Glad you find Bamboo helpful though!
